run build and lint on pr commits

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -24,10 +24,15 @@ references:
   # Job runs for develop branch only
   filter-develop-branch: &filter-develop-branch
     filters:
+      branches:
+        only: develop
+
+  filter-pr-branch: &filter-pr-branch
+    filters:
       tags:
         ignore: /.*/
       branches:
-        only: develop
+        ignore: develop
 
 # Container for all the builds
 executors:
@@ -81,11 +86,11 @@ commands:
             case $DEPLOY_TARGET_ENV in
               dev*)
                 DEPLOY_ENV=dev
-                BUILD_PARAMS=--sourceMap
+                BUILD_PARAMS=--source-map
               ;;
               test)
                 DEPLOY_ENV=test
-                BUILD_PARAMS=--sourceMap
+                BUILD_PARAMS=--source-map
               ;;
               staging)
                 DEPLOY_ENV=staging
@@ -95,7 +100,7 @@ commands:
               ;;
               *)
                 DEPLOY_ENV=dev
-                BUILD_PARAMS=--sourceMap
+                BUILD_PARAMS=--source-map
                 echo "Defaulting $DEPLOY_TARGET_ENV to dev environment"
               ;;
             esac
@@ -104,40 +109,6 @@ commands:
             echo "export BUILD_PARAMS=$BUILD_PARAMS" >> $BASH_ENV
             source $BASH_ENV
 
-  deploy-stored-build:
-    description: Deploy archived build to GAE
-    parameters:
-      study_key:
-        type: string
-    steps:
-      - checkout:
-          path: *repo_path
-      - setup-shared-env:
-          study_key: << parameters.study_key >>
-      - set-deployment-environment
-      - run:
-          name: Retrieve and expand build archive for << parameters.study_key >> with git SHA << pipeline.git.revision >>
-          command: |
-            set -u
-            # we are getting our builds from the one bucket
-            readvault.sh secret/pepper/prod/v1/conf .data.gcp.serviceKey | gcloud auth activate-service-account --key-file=-
-            TAR_FILE_URL_PATTERN="gs://${BUILDS_BUCKET}/${ANGULAR_PROJECT_NAME}/${ANGULAR_PROJECT_NAME}_*_${SHORT_GIT_SHA}.tar.gz"
-            echo "Looking for archive matching ${TAR_FILE_URL_PATTERN}"
-            TAR_FILE_URL=`gsutil ls $TAR_FILE_URL_PATTERN  | sort -r | head -1`
-
-            if [ -z $TAR_FILE_URL ]
-            then
-              echo "Could not find archive using pattern ${TAR_FILE_URL_PATTERN}"
-              exit 1
-            fi
-            TAR_FILE_PATH="/tmp/$(basename -- $TAR_FILE_URL)"
-            echo "Downloading ${TAR_FILE_URL} to ${TAR_FILE_PATH}"
-            gsutil cp  $TAR_FILE_URL $TAR_FILE_PATH
-            mkdir -p $OUTPUT_DIR && tar -xvf $TAR_FILE_PATH -C $OUTPUT_DIR
-            echo "Contents of extracted archive at $OUTPUT_DIR"
-            ls -l $OUTPUT_DIR
-      - deploy-exploded-build:
-          study_key: << parameters.study_key >>
 
   deploy-exploded-build:
     description: Deploy files to GAE
@@ -262,34 +233,6 @@ commands:
             source $BASH_ENV
 
 
-  run-linter-check:
-    description: "Run linter check"
-    steps:
-      - run:
-          name: Linter check
-          command: |
-            ng lint ddp-sdk
-            ng lint toolkit
-            ng lint $ANGULAR_PROJECT_NAME
-  run-tests:
-    description: "Run all tests"
-    steps:
-      - run:
-          name: ng test
-          command: |
-            mkdir -p /tmp/junit
-            ng test ddp-sdk --watch=false --browsers ChromeHeadlessNoSandbox --reporters junit
-            ng test toolkit --watch=false --browsers ChromeHeadlessNoSandbox --reporters junit
-            ng test $ANGULAR_PROJECT_NAME --watch=false --browsers ChromeHeadlessNoSandbox --reporters junit
-          environment:
-            JUNIT_REPORT_PATH: /tmp/junit/
-            JUNIT_REPORT_NAME: test-results.xml
-          when: always
-      - store_test_results:
-          path: /tmp/junit
-      - store_artifacts:
-          path: /tmp/junit
-
   build:
     description: "Build DDP study app"
     parameters:
@@ -321,31 +264,8 @@ commands:
           command: |
             set -u
             export NODE_OPTIONS="--max-old-space-size=4096"
-            ng build $ANGULAR_PROJECT_NAME $BUILD_PARAMS --prod --aot --base-href=/ --output-path=$OUTPUT_DIR --verbose=true --progress=true
+            ng build $ANGULAR_PROJECT_NAME $BUILD_PARAMS --configuration production --aot --base-href=/ --output-path=$OUTPUT_DIR --verbose=true --progress=true
 
-  store-app-build:
-    description: "Copy build to cloud storage"
-    steps:
-      - run:
-          name: Create build archive
-          command: |
-            set -u
-            DATE=`date +%F`
-            TAR_NAME="${ANGULAR_PROJECT_NAME}_${DATE}_${SHORT_GIT_SHA}.tar.gz"
-            TAR_PATH="/tmp/${TAR_NAME}"
-            # Save some ENV vars for in job downstream
-            echo "export TAR_NAME=$TAR_NAME" >> $BASH_ENV
-            echo "export TAR_PATH=$TAR_PATH" >> $BASH_ENV
-            cd ${OUTPUT_DIR}
-            tar -czvf ${TAR_PATH} .
-            echo "Tar file created at ${TAR_PATH}"
-            ls -l $TAR_PATH
-      - run:
-          name: Store build archive
-          command: |
-            set -u
-            readvault.sh secret/pepper/prod/v1/conf .data.gcp.serviceKey | gcloud auth activate-service-account --key-file=-
-            gsutil cp  ${TAR_PATH} "gs://${BUILDS_BUCKET}/${ANGULAR_PROJECT_NAME}/${TAR_NAME}"
 
   conditionally-launch-build-and-deploy:
     description: Launch build and deploy if project has changed
@@ -439,6 +359,55 @@ commands:
                 name: Halt job ENV=<< parameters.env >>
                 command: circleci-agent step halt
 
+  run-ui-unit-test:
+    description: Lint code and run ui unit tests for specified app
+    parameters:
+      study_key:
+        type: string
+    steps:
+      - setup-shared-env:
+          study_key: << parameters.study_key >>
+      - run:
+          name: Lint app code
+          command: |
+            ng lint $ANGULAR_PROJECT_NAME
+      - run:
+          name: Run ng ui unit tests
+          command: |
+            mkdir -p /tmp/junit
+            ng test $ANGULAR_PROJECT_NAME --watch=false --browsers ChromeHeadlessNoSandbox --reporters junit
+          environment:
+            JUNIT_REPORT_PATH: /tmp/junit/
+            JUNIT_REPORT_NAME: test-results.xml
+          when: always
+      - store_test_results:
+          path: /tmp/junit
+      - store_artifacts:
+          path: /tmp/junit
+
+  run-api-unit-test:
+    description: Lint code and run api unit tests for sdk and toolkit
+    steps:
+      - run:
+          name: Lint sdk and toolkit code
+          command: |
+            ng lint ddp-sdk
+            ng lint toolkit
+      - run:
+          name: Run sdk and toolkit api unit tests
+          command: |
+            mkdir -p /tmp/junit
+            ng test ddp-sdk --watch=false --browsers ChromeHeadlessNoSandbox --reporters junit
+            ng test toolkit --watch=false --browsers ChromeHeadlessNoSandbox --reporters junit
+          environment:
+            JUNIT_REPORT_PATH: /tmp/junit/
+            JUNIT_REPORT_NAME: test-results.xml
+          when: always
+      - store_test_results:
+          path: /tmp/junit
+      - store_artifacts:
+          path: /tmp/junit
+
 jobs:
   app-deploy:
     working_directory: *ng_workspace_path
@@ -450,8 +419,9 @@ jobs:
     steps:
       - build:
           study_key: << parameters.study_key >>
-      - run-linter-check
-      - run-tests
+      - run-ui-unit-test:
+          study_key: << parameters.study_key >>
+      - run-api-unit-test
       - deploy-exploded-build:
           study_key: << parameters.study_key >>
 
@@ -513,6 +483,7 @@ jobs:
           study_key: fon
 
   app-build:
+    description: Run build and store build artifacts to Google cloud storage
     working_directory: *ng_workspace_path
     executor:
       name: build-executor
@@ -522,8 +493,6 @@ jobs:
     steps:
       - build:
           study_key: << parameters.study_key >>
-      - run-linter-check
-      - run-tests
       - run:
           name: Short circuit - Don't store build artifacts if branch is a pull request
           command: |
@@ -533,9 +502,30 @@ jobs:
               echo "Skip store build"
               circleci-agent step halt
             fi
-      - store-app-build
+      - run:
+          name: Create build archive for << parameters.study_key >> with git SHA << pipeline.git.revision >>
+          command: |
+            set -u
+            DATE=`date +%F`
+            TAR_NAME="${ANGULAR_PROJECT_NAME}_${DATE}_${SHORT_GIT_SHA}.tar.gz"
+            TAR_PATH="/tmp/${TAR_NAME}"
+            # Save some ENV vars for in job downstream
+            echo "export TAR_NAME=$TAR_NAME" >> $BASH_ENV
+            echo "export TAR_PATH=$TAR_PATH" >> $BASH_ENV
+            cd ${OUTPUT_DIR}
+            tar -czvf ${TAR_PATH} .
+            echo "Tar file created at ${TAR_PATH}"
+            ls -l $TAR_PATH
+      - run:
+          name: Store build archive for << parameters.study_key >> with git SHA << pipeline.git.revision >>
+          command: |
+            set -u
+            readvault.sh secret/pepper/prod/v1/conf .data.gcp.serviceKey | gcloud auth activate-service-account --key-file=-
+            gsutil cp  ${TAR_PATH} "gs://${BUILDS_BUCKET}/${ANGULAR_PROJECT_NAME}/${TAR_NAME}"
+      
 
   deploy-stored-build-job:
+    description: Deploy archived build to GAE
     working_directory: *ng_workspace_path
     parameters:
       study_key:
@@ -543,19 +533,35 @@ jobs:
     executor:
       name: build-executor
     steps:
-      - deploy-stored-build:
+      - checkout:
+          path: *repo_path
+      - setup-shared-env:
+          study_key: << parameters.study_key >>
+      - set-deployment-environment
+      - run:
+          name: Retrieve and expand build archive for << parameters.study_key >> with git SHA << pipeline.git.revision >>
+          command: |
+            set -u
+            # we are getting our builds from the one bucket
+            readvault.sh secret/pepper/prod/v1/conf .data.gcp.serviceKey | gcloud auth activate-service-account --key-file=-
+            TAR_FILE_URL_PATTERN="gs://${BUILDS_BUCKET}/${ANGULAR_PROJECT_NAME}/${ANGULAR_PROJECT_NAME}_*_${SHORT_GIT_SHA}.tar.gz"
+            echo "Looking for archive matching ${TAR_FILE_URL_PATTERN}"
+            TAR_FILE_URL=`gsutil ls $TAR_FILE_URL_PATTERN  | sort -r | head -1`
+
+            if [ -z $TAR_FILE_URL ]
+            then
+              echo "Could not find archive using pattern ${TAR_FILE_URL_PATTERN}"
+              exit 1
+            fi
+            TAR_FILE_PATH="/tmp/$(basename -- $TAR_FILE_URL)"
+            echo "Downloading ${TAR_FILE_URL} to ${TAR_FILE_PATH}"
+            gsutil cp  $TAR_FILE_URL $TAR_FILE_PATH
+            mkdir -p $OUTPUT_DIR && tar -xvf $TAR_FILE_PATH -C $OUTPUT_DIR
+            echo "Contents of extracted archive at $OUTPUT_DIR"
+            ls -l $OUTPUT_DIR
+      - deploy-exploded-build:
           study_key: << parameters.study_key >>
 
-  app-run-tests-job:
-    working_directory: *ng_workspace_path
-    executor:
-      name: build-executor
-    steps:
-      - checkout-code
-      - setup-shared-env:
-          study_key: << pipeline.parameters.study_key >>
-      - run-linter-check
-      - run-tests
 
   playwright-build:
     executor: build-executor
@@ -663,6 +669,27 @@ jobs:
           path: playwright-e2e/html-test-results
           destination: html-test-results
 
+  api-unit-test:
+    description: Lint code and run api unit tests for sdk and toolkit
+    working_directory: *ng_workspace_path
+    executor:
+      name: build-executor
+    steps:
+      - checkout-code
+      - run-api-unit-test
+
+  ui-unit-test:
+    description: Lint code and run ui unit tests for specified app
+    working_directory: *ng_workspace_path
+    executor:
+      name: build-executor
+    parameters:
+      study_key:
+        type: string
+    steps:
+      - checkout-code
+      - run-ui-unit-test:
+          study_key: << parameters.study_key >>
 
 parameters:
   study_key:
@@ -689,6 +716,29 @@ parameters:
 workflows:
   version: 2
 
+  build-test-pr:
+    # Automatically launched on every PR commit
+    jobs:
+      - app-build:
+          <<: *filter-pr-branch
+          name: << matrix.study_key >>-build
+          matrix:
+            alias: app-build-and-store
+            parameters:
+              study_key: [ basil, osteo, angio, brain, mbc, mpc, atcp, rgp, esc, prion, pancan, singular, brugada, lms ]
+      - ui-unit-test:
+          <<: *filter-pr-branch
+          name: << matrix.study_key >>-ui-unit-test
+          matrix:
+            alias: app-ui-unit-test
+            parameters:
+              study_key: [ basil, osteo, angio, brain, mbc, mpc, atcp, rgp, esc, prion, pancan, singular, brugada, lms ]
+      - api-unit-test:
+          <<: *filter-pr-branch
+      - playwright-build:
+          <<: *filter-pr-branch
+
+
   api-build-and-store-workflow:
     # Build study specified in api call
     when:
@@ -699,6 +749,9 @@ workflows:
     jobs:
       - app-build:
           study_key: << pipeline.parameters.study_key >>
+      - ui-unit-test:
+          study_key: << pipeline.parameters.study_key >>
+      - api-unit-test
 
   api-deploy-workflow:
     # Deploy a study build to environment specified in api call
@@ -722,7 +775,9 @@ workflows:
           - not:
               equal: ["UNKNOWN", << pipeline.parameters.study_key >>]
       jobs:
-        - app-run-tests-job
+        - api-unit-test
+        - ui-unit-test:
+            study_key: << pipeline.parameters.study_key >>
 
   playwright-test-workflow:
     # Triggered by CI API (for example, run_ci.sh)
@@ -744,10 +799,7 @@ workflows:
     unless: << pipeline.parameters.do-builds >>
     jobs:
       - conditionally-launch-build-and-deploy-all-job:
-          filters:
-            branches:
-              only:
-                - develop
+          <<: *filter-develop-branch
 
   build-and-deploy-workflow:
     when:
@@ -781,6 +833,11 @@ workflows:
       - app-build:
           <<: *build-and-store-filters
           study_key: << pipeline.parameters.study_key >>
+      - ui-unit-test:
+          <<: *build-and-store-filters
+          study_key: << pipeline.parameters.study_key >>
+      - api-unit-test:
+          <<: *build-and-store-filters
 
   deploy-all-apps-workflow:
     jobs:
