WIP config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -16,7 +16,6 @@ executors:
     working_directory: ~/repo
 
 commands:
-
   build-and-deploy-study:
     description: "Build and deploy angular study website"
     parameters:
@@ -109,6 +108,19 @@ commands:
           name: <<parameters.study_key>> deploy to GAE
           command: gcloud app deploy --version="${CIRCLE_SHA1}" --project "broad-ddp-${ENVIRONMENT}" "${ANGULAR_PROJECT_DIR_PATH}/app.yaml"
           working_directory: ~/repo/ddp-workspace
+  setup-shared-env:
+    description: "Setup shared ENV vars"
+    parameters:
+      study_key:
+        type: string
+    steps:
+      - run:
+          command: |
+            echo 'export ANGULAR_PROJECT_NAME=ddp-<<parameters.study_key>>' >> $BASH_ENV
+            echo 'export ANGULAR_PROJECT_DIR_PATH=projects/ddp-<<parameters.study_key>>' >> $BASH_ENV
+            echo "export SHORT_GIT_SHA=`echo '<< pipeline.git.revision >>' | cut -c 1-7`" >> $BASH_ENV
+            echo 'export BUILDS_BUCKET=ddp-angular-builds' >> $BASH_ENV
+            source $BASH_ENV
   setup-build-workspace:
     description: "Setup workspace used by all projects"
     steps:
@@ -126,30 +138,25 @@ commands:
             - ./node_modules
   build-app:
     description: "Build DDP study app"
-    parameters:
-      study_key:
-        type: string
     steps:
       - run:
-          name: <<parameters.study_key>> ng build
+          name: ng build $ANGULAR_PROJECT_NAME
           command: |
-            ANGULAR_PROJECT_NAME=ddp-<< parameters.study_key >>
+            set -u
             ng build $ANGULAR_PROJECT_NAME --base-href=/ --output-path=dist/$ANGULAR_PROJECT_NAME --verbose=true --progress=true
           working_directory: ~/repo/ddp-workspace
+
   store-app-build:
     description: "Copy build to cloud storage"
-    parameters:
-      study_key:
-        type: string
     steps:
       - run:
           name: Create build archive
           command: |
-            ANGULAR_PROJECT_NAME=ddp-<< parameters.study_key >>
-            GIT_SHA=`git rev-parse --verify --short HEAD`
+            set -u
             DATE=`date +%F`
-            TAR_NAME="${ANGULAR_PROJECT_NAME}_${DATE}_${GIT_SHA}.tar.gz"
+            TAR_NAME="${ANGULAR_PROJECT_NAME}_${DATE}_${SHORT_GIT_SHA}.tar.gz"
             TAR_PATH="/tmp/${TAR_NAME}"
+            # Save some ENV vars for in job downstream
             echo "export ANGULAR_PROJECT_NAME=$ANGULAR_PROJECT_NAME" >> $BASH_ENV
             echo "export TAR_NAME=$TAR_NAME" >> $BASH_ENV
             echo "export TAR_PATH=$TAR_PATH" >> $BASH_ENV
@@ -159,10 +166,69 @@ commands:
       - run:
           name: Store build archive
           command: |
-            BUILDS_BUCKET=ddp-angular-builds
+            set -u
             ./readvault.sh secret/pepper/dev/v1/conf .data.gcp.serviceKey | gcloud auth activate-service-account --key-file=-
             gsutil cp  ${TAR_PATH} "gs://${BUILDS_BUCKET}/${ANGULAR_PROJECT_NAME}/${TAR_NAME}"
           working_directory: ~/repo
+
+  app-build-and-store:
+    description: Run build and store archive of it
+    parameters:
+      study_key:
+        type: string
+    steps:
+      - setup-build-workspace
+      - setup-shared-env:
+          study_key: << parameters.study_key >>
+      - build-app
+      - store-app-build
+  deploy-stored-build:
+    description: "Deploy build archive to GAE"
+    parameters:
+      environment:
+        type: string
+      study_key:
+        type: string
+    steps:
+      - checkout:
+          path: ~/repo
+      - setup-shared-env:
+          study_key: << parameters.study_key >>
+      - run:
+          name: Add add more environment variables used
+          command: |
+            echo 'export ENVIRONMENT=ddp-<<parameters.environment>>' >> $BASH_ENV
+            source $BASH_ENV
+      - run:
+          name: Retrieve build archive for << parameters.study_key >> with git SHA ${SHORT_GIT_SHA}
+          command: |
+            set -u
+            # we are getting our builds from the one bucket
+            ./readvault.sh secret/pepper/dev/v1/conf .data.gcp.serviceKey | gcloud auth activate-service-account --key-file=-
+            TAR_FILE_URL_PATTERN="gs://${BUILDS_BUCKET}/${ANGULAR_PROJECT_NAME}/${ANGULAR_PROJECT_NAME}_*_${SHORT_GIT_SHA}.tar.gz"
+            TAR_FILE_URL=`gsutil ls $TAR_FILE_URL_PATTERN  | sort -r | head -1`
+            if [ -z $TAR_FILE_URL ]
+            then
+              echo "Could not find archive using pattern ${TAR_FILE_URL_PATTERN}"
+              exit 1
+            fi
+            TAR_FILE_PATH="/tmp/$(basename -- $TAR_FILE_URL)"
+            gsutil cp  $TAR_FILE_URL $TAR_FILE_PATH
+            # OUTPUT_DIR="/tmp/$(basename -- $TAR_FILE_URL .tar.gz)"
+            cd ~/repo/ddp-workspace
+            # this is where app.yaml files are pointing for assets
+            OUTPUT_DIR="${ANGULAR_PROJECT_DIR_PATH}/dist"
+            mkdir -p $OUTPUT_DIR && tar -xvf $TAR_FILE_PATH -C $OUTPUT_DIR
+      - run:
+          name: setup gcloud context to deploy to << parameters.environment >>
+          command: |
+            set -u
+            ./readvault.sh secret/pepper/${ENVIRONMENT}/v1/conf .data.gcp.serviceKey | gcloud auth activate-service-account --key-file=-
+            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
+      - run:
+          name: deploy to GAE
+          command: gcloud app deploy --version="${SHORT_GIT_SHA}" --project "broad-ddp-${ENVIRONMENT}" "${ANGULAR_PROJECT_DIR_PATH}/app.yaml"
+          working_directory: ~/repo/ddp-workspace
 
 jobs:
   osteo-build-and-deploy:
@@ -177,11 +243,16 @@ jobs:
     executor:
       name: commit-executor
     steps:
-      - setup-build-workspace
-      - build-app:
+      - app-build-and-store:
           study_key: osteo
-      - store-app-build:
+  osteo-deploy-only:
+    executor:
+      name: commit-executor
+    steps:
+      - setup-build-env:
           study_key: osteo
+      - deploy-stored-build:
+          environment: dev
   angio:
     executor:
       name: commit-executor
@@ -221,11 +292,11 @@ workflows:
             branches:
               only:
                 - /^angular-appengine-deployment.*/
-#      - osteo-deploy-only:
-#          filters:
-#            tags:
-#              only:
-#                - /^angular_test_.*/
+      - osteo-deploy-only:
+          filters:
+            tags:
+              only:
+                - /^angular_test_.*/
       - angio:
           filters:
             branches:
